version: '3'
services:
  server:
    # image: jr-cms-15
    image: node:14
    ports:
      - 3000:3000
    container_name: jr-cms-15_server
    depends_on:
      - mongo
    environment:
      - JWT_KEY=value
      - CONNECTION_STRING=mongodb://mongo/jrCMS15
    volumes:
      - ./:/app
    command: >
      sh -c "cd /app && rm -rf node_modules/ && npm i && npm run dev"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: jr-cms-15_mongo