name: jr cms 15 CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [14.x, 12.x]
    # mongodb-version: ['4','5']
    # steps:
    #   - name: Git checkout
    #     uses: actions/checkout@v2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          # node-version: ${{ matrix.node_version }}
      - run: npm install
      - run: npm test
